### ISSUE TITLE
[DISCUSSION] Release 7.0.0^W 7.1.0

### ISSUE THREAD

**Issue by janl** [apache/couchdb-nano#104]
Heya,

this issue for discussing the release of ~7.0.0~ 7.1.0 now that #98 has landed and [7.0.0 has been released](https://lists.apache.org/thread.html/3d8439a195fd750c2cf759e45af5e7c89db9a646297efab124f221f9@%3Cuser.couchdb.apache.org%3E)

Open questions:

- [ ] are there any other PRs we want to land?
- [ ] are there any issues that don’t have a PR yet, but should be fixed?
- [ ] are we maintaining 6.x and 7.x in parallel, or do we suggest folks move up to 7.x asap? Are there any BC break considerations to be made?
- [ ] should we release 7.0.0 on the `next` dist-tag for a while before making it latest? or should we go straight to `latest`?
- [x] ~update dependencies~ this was prompted by `npm audit` showing vulnerabilities, but these are in devDeps of sub-deps, who themselves have [no intention to move things along](https://github.com/jshint/jshint/pull/3296) // not great to have the dependency badge show red, but what can one do :/
- [ ] update _other_ dependencies:
  - [ ] tape-it: See https://github.com/apache/couchdb-nano/pull/105
  - [ ] jshint is ~EOL~done, there are a few tools that help migrate an `.jshintrc` to an `.eslintrc`: https://github.com/vs-archive/eslint-rules-mapper // alternatively, we can move to `standard` and begone with the configuration.
  - [ ] jscs is also EOL and I’m not sure why we need two linters
  - [ ] endswith: https://github.com/apache/couchdb-nano/pull/106

Feel free to add your own open questions by editing this issue.

cc @garrensmith @glynnbird @jo

**Comment by glynnbird** [comment]
- *standard* JS code standard replaces others
- endsWith fixed
- tape-it updated
- fixed bug where users using the callback style were dealing with Promise rejections

**Comment by glynnbird** [comment]
* documentation fixes
* removed obsolete spatial functions
* multi-view query support
* example code fixes

**Comment by glynnbird** [comment]
> are we maintaining 6.x and 7.x in parallel, or do we suggest folks move up to 7.x asap? Are there any BC break considerations to be made?
I hadn't anticipated making any further releases in the 6.x space, but I guess we'll see how the demand pans out. I don't know of any other compatibility issues. The Migration Guide describes mitigating actions that users need to consider when moving from 6 to 7. If a user has a callback-heavy codebase, they may use Nano 7 without issues unless they are using the streamed responses.

> should we release 7.0.0 on the next dist-tag for a while before making it latest? or should we go straight to latest
I hadn't anticipated this possibility so 7.0.0 == latest at the moment. Obviously, if users want to pin to an earlier version range they can
