### ISSUE TITLE
Use new endpoints for multiple queries in 2.2.0+

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-nano#109]
With https://github.com/apache/couchdb/issues/820 we have landed new endpoints for multi-queries that are much more efficient for /_all_docs, /_design_docs, /_local_docs, and of course JS views. The old view multi-query endpoint is being deprecated.

Please detect 2.2.0 in the `GET /` endpoint and move to these new endpoints where possible.

This is mentioned in the release notes here (point 3): http://docs.couchdb.org/en/2.2.0/whatsnew/2.2.html
And of course is explained in the main API reference section.

**Comment by adamsaeid** [comment]
Does anybody mind if I have a go at implementing this over the weekend?

**Comment by garrensmith** [comment]
Awesome. Please go for it. Let me know if I can help

**Comment by adamsaeid** [comment]
Made a start on this. Will hopefully have a PR some point this week
