### ISSUE TITLE
insertDocument API broken backwards compatibility (cannot update document)

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#11]
[Original issue](https://github.com/dscape/nano/issues/288)

__nacho4d__
Hello everyone.
Thanks for this awesome library!

I got the latest version of nano and realized I was not able to update documents anymore when using some old code. I found there were some style changes in commit: 848caf7 that made the API not to work with old code

The exact change can be found here:
848caf7#commitcomment-11989091

I am not sure about the policy for addressing this kind of things. The commit is like 9 months old and since nobody else seems to have noticed this then I guess updating the documentation to highlight this kind of changes would be enough. Otherwise I can make I small pul request to support both :)

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
