### ISSUE TITLE
db.fetch(): Cannot set property 'include_docs' of undefined

### ISSUE THREAD

**Issue by gambolputty** [apache/couchdb-nano#114]
Hi!

I am using `db.fetch({'keys': keyArr})` to retrieve multiple docs at the same time, as described in README.md

## Expected Behavior
Getting all docs specified in `keyArr`. 

## Current Behavior
I am getting an error:
```
TypeError: Cannot set property 'include_docs' of undefined
    at Object.fetchDocs [as fetch] (G:\Git\project\web\node_modules\nano\lib\nano.js:566:28)

```

## Possible Solution
On line 566 in nano.js `opts` is undefined. If I pass an extra empty object to the function call, everything works as expected and I am getting my docs: `db.fetch({'keys': keyArr}, {})`

## Your Environment
* Version used: 7.0.0
* Node version: v8.9.4
* CouchDB version: 2.1.1
* Operating System: Windows 10

**Comment by glynnbird** [comment]
Thanks for the ticket @gambolputty . I've verified the problem and there is a fix coming in the the `issue112` branch.

**Comment by glynnbird** [comment]
In fact, for the sake of clarity I'll fix in a new branch (with tests).

**Comment by glynnbird** [comment]
After the merge of the `issue112` branch, this issue is fixed in the master branch and will form part of the next release.

**Comment by gambolputty** [comment]
You are welcome!
