### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by rmshkmr** [apache/couchdb-nano#119]
![selection_009](https://user-images.githubusercontent.com/11422153/44707915-6f73ba00-aac3-11e8-96ce-0a227f5654fb.png)
413 request entity too large while updating the document

**Comment by tephyr** [comment]
Did you hit this problem with CouchDB version 2.1.0?  If so, it may be related to this CouchDB change: [re-raise max_http_request_size to 4GB #1446](https://github.com/apache/couchdb/pull/1446).  CouchDB version 2.1.0 had a 64MB request size limit.

[What's new in CouchDB v2.2.0](http://docs.couchdb.org/en/2.2.0/whatsnew/2.2.html) has more info.

**Comment by rmshkmr** [comment]
Its a couchdb error. it gets solved. Thanks
