### ISSUE TITLE
Support _selector based filtering for changes feed

### ISSUE THREAD

**Issue by danielpaull** [apache/couchdb-nano#121]
It appears that the use of selectors (same as is used in Mango queries) to filter a changes feed is not supported.  This would be a useful addition for cases where results of a Mango query are kept up to date by a client.

This is described in Section 10.3.9.2.2 of the CouchDB current documentation (http://docs.couchdb.org/en/stable/api/database/changes.html).

## Your Environment

* Version used: 7.0.0
* Browser Name and version: Node.js
* Operating System and version (desktop or mobile): Windows x64
* Link to your project:

**Comment by danielpaull** [comment]
This may entirely be an issue for Follow.  There is a related issue reported there:

https://github.com/cloudant-labs/cloudant-follow/issues/71

**Comment by manobi** [comment]
I really need this feature.

**Comment by manobi** [comment]
@danielpaull did you found a workaround for this?

**Comment by danielpaull** [comment]
@manobi  - no, I didn't find a work around and resorted to polling for the case I had.  An alternative would be to use PouchDB with the HTTP adaptor to access CouchDB because it supports filtering of the changes feed by selectors.

**Comment by SENSEi-James** [comment]
Seems to be working for me as follows:
```
const feed = couchDb.use(db).follow({
  since: 'now',
  include_docs: true,
  filter: '_selector',
  request: {
    method: 'POST',
    body: JSON.stringify({selector: {documentProperty: {$eq: 'value'}}})
  }
});

feed.on('change', change => console.log('change: ', change));
```

**Comment by lunedam-git** [comment]
If you're not after a continuous feed but want to use nano...

```
const nano = require('nano')('https://username:password@mycouch.db.server:5984');

const selectorJSON = {
  selector: {
    $or: [ { docType: 'post' }, { docType: 'comment' } ]
  }
};

const opts = {
  db: 'MYDB',
  method: 'POST',
  path: '_changes',
  qs: { since: 'now', include_docs: true, filter: '_selector' },
  body: selectorJSON
};

nano.request(opts).then(res => {
  console.log(util.inspect(res));
});
```
Of course, you could just as easily use [request](https://www.npmjs.com/package/request) to start off with?
