### ISSUE TITLE
No types for `createIndex`

### ISSUE THREAD

**Issue by darky** [apache/couchdb-nano#129]
## Expected Behavior

Types exists

## Current Behavior

Not exists

## Possible Solution

Need add types

## Steps to Reproduce (for bugs)

```ts
couch.use('name').createIndex
```

```
[ts] Property 'createIndex' does not exist on type 'DocumentScope<{}>'.
```

## Context

TypeScript programming

**Comment by sureshappana** [comment]
Yes, I also observed it today and found it is missing. Shall I raise PR for this fix?

**Comment by mkeology** [comment]
any updates to this issue ? Having a TS Type for createIndex in an essential function for me.

**Comment by janl** [comment]
PRs welcome

**Comment by lesterbx** [comment]
I'm doing this if nobody did it already
