### ISSUE TITLE
Invalid typings for MangoSelector

### ISSUE THREAD

**Issue by twawszczak** [apache/couchdb-nano#137]
https://github.com/apache/couchdb-nano/blob/1f8faf4e78d85e133f7070bf7bd8ba028ca6cf77/lib/nano.d.ts#L1184

Item of mango selector should also have possibility to contain array of MangoSelector (for example for `$or`, `$end` conditions)

current: 
```
interface MangoSelector {
    [key: string]: MangoSelector | MangoValue | MangoValue[];
  }
```

better:
```
interface MangoSelector {
    [key: string]: MangoSelector | MangoSelector[], MangoValue | MangoValue[];
  }
```

**Comment by samriddhi** [comment]
Another thing to add is on the `MangoValue` to include null since that is a type possible in couchDb 
`type MangoValue = number | string | Date | boolean| null;`

**Comment by roikoren755** [comment]
Any news on this?

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
