### ISSUE TITLE
statusCode: 500 

### ISSUE THREAD

**Issue by rmshkmr** [apache/couchdb-nano#146]
I added a new admin and added the admin in permission tab and deleted that. Now i'm unable to update the document.

Error;
name: 'Error',
 scope: 'couch',
 statusCode: 500
![screenshot from 2019-02-25 17-59-36](https://user-images.githubusercontent.com/11422153/53338757-838d5c80-392a-11e9-9d11-90000ddbb47a.png)

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
