### ISSUE TITLE
Misleading example value for docname in Attachments functions

### ISSUE THREAD

**Issue by m-lukas** [apache/couchdb-nano#165]
## Expected Behavior

From the examples, you should directly understand what is meant with the team "docname".
In this case it's just the id of the document and the example should be choosen to understand that immediately. In best case there is additionally an definition for docname in general to cause no confusions.

## Current Behavior

In the example for the attachment insert:
```
const fs = require('fs');

fs.readFile('rabbit.png', (err, data) => {
  if (!err) {
    alice.attachment.insert('rabbit', 'rabbit.png', data, 'image/png',
      { rev: '12-150985a725ec88be471921a54ce91452' }).then((body) => {
        console.log(body);
    });
  }
});
```
it uses rabbit as docname, similar to the filename.
However since there is no definition for docname in general and the _id fields in my database are mostly hashes, I as complete beginner with CouchDB didn't realize that 'rabbit' is the _id of document but instead thought it's an shorter identifier? for the file. This caused an 409 error with the error message *"missing_rev"* (rev was existing parameter) which was quite missleading and it took me several hours to find the mistake.
There is also a similar Issue #15 .

## Possible Solution

I think it would be helpful to specify more what docname means (for example add a short definition at the beginning of the README). Additionally it would be helpful to change the docname 'rabbit' to something different in this example. 

## Steps to Reproduce (for bugs)

https://github.com/apache/couchdb-nano#dbattachmentinsertdocname-attname-att-contenttype-params-callback

The error can be triggered by using a non-existing docname.

## Context

I wanted to insert an attachment in my couchDB instance but used a non-existing docname (filename without mime type).

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
