### ISSUE TITLE
get part of an attachment using http range requests

### ISSUE THREAD

**Issue by pieper** [apache/couchdb-nano#166]
Couchdb supports [HTTP Range Requests](http://docs.couchdb.org/en/stable/api/document/attachments.html#api-doc-attachment-range) but as far as I could see nano does not expose that.
## Expected Behavior

I would expect that the get/getAsStream opts object would include a range member so that resulting stream would only include the specified byte range of the attachment.

## Current Behavior

As far as I can tell it's only possible to get the full attachment data.

## Possible Solution

As noted in the Couchdb documentation linked above, it should be as simple as adding a header like `Range: bytes 0-12` when GETing the attachment.

## Steps to Reproduce (for bugs)

Don't have a way to reproduce - this is more of a feature question.

## Context

We are working on an implementation of the [DICOMweb standard](https://www.dicomstandard.org) whereby medical image volumes and other data are accessed over a rest api.  [Our implementation](https://github.com/dcmjs-org/dicomweb-server) uses fastify and couchdb (nano) and it mostly works well.  The metadata is stored in couchdb and the image data is in attachments.  However the DICOMweb API supports requesting a single frame (slice) out of a full volume and we'd like to be able to access that efficiently using a range request to pull just the needed frame information from the volume.

## Your Environment

* Version used: 7.1.1
* Link to your project: https://github.com/dcmjs-org/dicomweb-server

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
