### ISSUE TITLE
replicating a firestore

### ISSUE THREAD

**Issue by muscaiu** [apache/couchdb-nano#168]
Hello, i have decided to give up firebase and use a local db for my RPi project.
So, because i can't use a decent MongoDB/Mongoose version because of the 32 architecture, i have decided to try CouchDB.

The project is controling a simple on/off relay and storing the data to use for charts.
So basically i need a couple of tables 'status' and 'mode' in which i will insert values like 

for mode: 
[{value: 'auto', createdAt: date()}, {value: 'manual', createdAt: date()} ...]

for status
[{value: true, createdAt: date()}, {value: false, createdAt: date()} ...]

The problem is, i can't find a good way to structrue the data in a tabular form and yes i know this is a document based DB, but still it should be easy to find.
I could use like 2 databases for each of my tables status and mode, but i don't think that's how i supposed to be doing it.

This is what i have so far, but it's wrong.

```
const nano = require('nano')('http://192.168.1.10:5984');
const pompadb = nano.use('pompadb')

router.post('/create', async (req, res) => {
  const mode = await pompadb.insert({
    value: 'manual',
    createdAt: Date.now()
  }, 'mode')
  return res.send(mode);
});
```

And this is how the firestore looks like:
[
![firestore](https://user-images.githubusercontent.com/11426309/59965970-ffd12e80-951d-11e9-9e7b-3241d92a82e5.png)
](url)

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.

You can use one db and add a "type" property for your documents like:

```json
{
  "type": "mode", // or status
  "value": "auto",
  "createdAt": ...
}
```
