### ISSUE TITLE
improvement: it would be helpful to explain how to sort in the readme

### ISSUE THREAD

**Issue by BananaAcid** [apache/couchdb-nano#171]
There is no `sort` mentioned in the readme. I would expect it to work with db.list() it it seems it is exclusive to `couch's /find`.
Clarifying that, would help non-pros (aka noobs) like me. It states `params` everywhere, but not what they are restricted to, as far as I can tell. Translating the CouchDB docs needs some experience.

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
