### ISSUE TITLE
Documentation - cookie authentication

### ISSUE THREAD

**Issue by SinanGabel** [apache/couchdb-nano#180]
Re. Documentation part about cookie authentication.

The line that states:

`const nano = require('nano')({url: 'http://localhost:5984', requestDefaults: {jar:true}})`

will fail if couchdb is configured with the following setting:

[couch_httpd_auth] 
require_valid_user = true; 

A solution is to add user_name and user_password to the call so it reads:

`const nano = require('nano')({url: 'http://user_name:user_password@localhost:5984', requestDefaults: {jar:true}})`

**Comment by big-r81** [comment]
You can use your solution or do a `POST` request with username/password as payload.
