### ISSUE TITLE
multipart.get does not return Buffer using promises

### ISSUE THREAD

**Issue by nykewl** [apache/couchdb-nano#185]
The db.multipart.get(docname, [params], [callback]) method ([documentation](https://github.com/apache/couchdb-nano#dbmultipartgetdocname-params-callback)) does not return a buffer when using the promises. It does work as expected when using the callback pattern.

I'm using nano v8.1.0 and CouchDB v.2.3.1.

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
