### ISSUE TITLE
Request is deprecated

### ISSUE THREAD

**Issue by glynnbird** [apache/couchdb-nano#196]
The [request library](https://www.npmjs.com/package/request) which is used extensively by this library is now deprecated. We need to pick an alternative, possibly [axios](https://www.npmjs.com/package/request)?

**Comment by garrensmith** [comment]
I’m a big fan of axios


________________________________

**Comment by glynnbird** [comment]
I think it would be simple enough to swap out the basic GET / POST / PUT / DELETE / HEAD operations for JSON payloads with axios.

- There would be API changes with the streaming API calls i.e. the `...AsStream` functions would no longer return a Request object
- can't see support for the COPY HTTP verb
- don't know what would happen to `multipart/related` API calls

It would probably need a nano 9.x release - I can take a look after the next 8.x release.

**Comment by glynnbird** [comment]
Release >=9.0.0 use axios.
