### ISSUE TITLE
anonymous functions transpiled with babel don't work with _design docs in couchdb

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#20]
[Original issue](https://github.com/dscape/nano/issues/309)

__export-mike__
Hi I've been using nano and cradle and both libraries seem to have this problem,

possibly this change should be fixed in couchdb.

flatiron/cradle#306

Have you encountered this issue before? How else could it be fixed?

__export-mike__
update from @janl flatiron/cradle#306 (comment)

__chirsfosterelli__
For what it's worth, we've dealt with that by doing this:
```javascript
const validate = function(newDoc, savedDoc, userCtx) {
   // Content here
}.toString()
```
This results in validate being a stringified function that can be passed to Nano, and babel will not name it.

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
