### ISSUE TITLE
The `queries` parameter is no longer supported at this endpoint

### ISSUE THREAD

**Issue by creativityjuice** [apache/couchdb-nano#213]
## Expected Behavior

The _view_ method is no longer working since my upgrade to CouchDB 3.0. Apparently, Nano send the request to a view as a POST with search parameters in the body with this form { "queries": ... }. 

## Current Behavior

Here is the error I get : "Error: The `queries` parameter is no longer supported at this endpoint"
And the stacktrace :
at Request._callback (***/node_modules/nano/lib/nano.js:168:15)
at Request.self.callback (***/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.EventEmitter.emit (domain.js:466:23)
at Request.<anonymous> (***/node_modules/request/request.js:1154:10)
at Request.emit (events.js:198:13)
at Request.EventEmitter.emit (domain.js:466:23)
at IncomingMessage.<anonymous> (***/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at IncomingMessage.EventEmitter.emit (domain.js:466:23)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

## Possible Solution

I'll rollback to CouchDB 2.3 in the mean time

## Steps to Reproduce (for bugs)
Here is the content of the request :
{ method: 'POST',
headers:
{ 'content-type': 'application/json',
accept: 'application/json' },
uri: 'http://localhost:5984/***/_design/v*/_view/***',
body:
'{"queries":[{"startkey":["25ea7f29-3246-41d9-a45b-280837c087fe"],"endkey":["25ea7f29-3246-41d9-a45b-280837c087fe",{}],"include_docs":true},{"startkey":["12bcdbc6-57dd-48bb-a45f-32c9731ebcf9"],"endkey":["12bcdbc6-57dd-48bb-a45f-32c9731ebcf9",{}],"include_docs":true}]}',
qsStringifyOptions: { arrayFormat: 'repeat' } },
headers:
{ uri:'http://localhost:5984/***/_design/v*/_view/***',
statusCode: 400,
'cache-control': 'must-revalidate',
connection: 'close',
'content-type': 'application/json',
date: 'Tue, 10 Mar 2020 10:15:04 GMT',
'x-couch-request-id': '27e5536e4a',
'x-couchdb-body-time': '0' },
errid: 'non_200',
description: 'couch returned 400' }

## Your Environment

* Version used: Nano 8.2.2 / CouchDB 3.0.0
* Browser Name and version: Firefox 73.0.1
* Operating System and version (desktop or mobile): Ubuntu 18.04
* Link to your project:

Thanks for all ;)

**Comment by glynnbird** [comment]
As the [release notes for CouchDB 3](https://docs.couchdb.org/en/latest/whatsnew/3.0.html#version-3-0-0) state, the queries parameter is no longer supported and is replaced by a [queries endpoint](https://docs.couchdb.org/en/latest/api/ddoc/views.html#api-ddoc-view-multiple-queries). The queries endpoint isn't directly modelled as function call, but you can create a custom request e.g you can do something like:

```js
const q = {
    "queries": [
        {
            "keys": [
                "meatballs",
                "spaghetti"
            ]
        },
        {
            "limit": 3,
            "skip": 2
        }
    ]
}
const req = {
  method: 'post',
  db: 'mydb',
  path: '_design/mydesigndoc/_view/myview/_queries',
  body: q
}
const result = await db.request(req)
```

**Comment by arslan-creator** [comment]
So I can't use nano anymore?
`.view` is now failing with The `queries` parameter is no longer supported at this endpoint

**Comment by janl** [comment]
@arslan-creator @glynnbird showed you an example of how to do what you want with nano.

**Comment by arslan-creator** [comment]
@janl if I try it I get 
`{ Error: Only GET,POST,HEAD allowed`

**Comment by janl** [comment]
can you show the exact code you are running?

**Comment by arslan-creator** [comment]
```
    const couchDB = nano(dbUrl);
    const body = {
        include_docs: true,
        descending: false,
        queries: queryParams,
    };
    const req = {
        method: 'post',
        db: 'mydb',
        path: '_design/myDesign/_view/myView/_queries',
        body,
    };
    const result = await couchDB.request(req);
```

**Comment by janl** [comment]
might be missing a leading `/` in the `path`? can you show the couch log entry for this?

**Comment by arslan-creator** [comment]
Adding the leading `/` didn't help.
Here is the corresponding log entry:
`[notice] 2020-06-03T13:25:43.770314Z couchdb@localhost <0.28308.2> c6a8dd72b3 127.0.0.1:5984 127.0.0.1 admin POST /mydb/_design/myDesign/_view/myView/_queries 405 ok 9

**Comment by arslan-creator** [comment]
Found out what what causing this. I used `_queries` instead of `queries` at the end of the path 🤦‍♂️
