### ISSUE TITLE
stale ok for partial retrieval while indexing in progress

### ISSUE THREAD

**Issue by hamedminaee** [apache/couchdb-nano#214]
Hello team,

I am using nano and this is how I call the design to get data back:

db.search("searchAll", "searchAll", {
      include_docs: true,
      limit: limit >= 0 ? limit : 10,
      bookmark,
      counts,
      query: query && query.length > 0 ? query : "*:*",
      sort,
    })

so now I need to add a stale: ok which tells couch do not care if the indexing is done just return the result partially anytime this is called.
Does Nano  handle that? 
how can I pass stale ok to nano ?

**Comment by glynnbird** [comment]
Nano just passes all options you supply to CouchDB. See [this blog](https://blog.cloudant.com/2018/11/06/What-is-stale-update-and-stable.html) on how updates are triggered or not by queries.
