### ISSUE TITLE
wrong database getting synced in couchdb

### ISSUE THREAD

**Issue by soubhikchatterjee** [apache/couchdb-nano#218]
I am using chrome and pouchdb to sync data to a remote couchdb data. I have a remote dev couchdb database that i use for testing purpose and a remote production CouchDB.

when I run chrome, my application syncs the data from the remote db and store in local electron's pouchdb and vice versa.

Things are fine but when I change the remote database URL from dev to prod, the locally stored dev data gets synced to prod db.

Is there any way (programmatically) I can stop this from happening?

PS: I know this is not a nano issue, but i couldn't find a better place to ask this or maybe someone here has already fixed this.

**Comment by glynnbird** [comment]
Definitely not a nano issue.

I think you're going to have to rewrite your app so that it writes a to a "prod" database when in prod mode and a "dev" database when in dev mode. i.e make the remote URL and the local database name part of the config that defines the environment.
