### ISSUE TITLE
Protocol https not suported

### ISSUE THREAD

**Issue by armanriazi** [apache/couchdb-nano#224]
When I set https url cloudant db I get this error
require("nano")("https://u:p@cloudanturl").use("mydb");

> Error: Protocol \"https\" not supported. Expected \"http:\"\n    at new ClientRequest (_http_client.js:131:11)\n    at Object.request (http.js:38:10)\n    at Object.request (https.js:239:15)\n    at Request.start (/home/node/app/production/vidly-api/node_modules/nano/node_modules/request/request.js:751:32)\n    at Request.write (/home/node/app/production/vidly-api/node_modules/nano/node_modules/request/request.js:1491:10)\n    at end (/home/node/app/production/vidly-api/node_modules/nano/node_modules/request/request.js:549:18)\n    at Immediate.<anonymous> (/home/node/app/production/vidly-api/node_modules/nano/node_modules/request/request.js:578:7)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5
> #

If I use this code it will be ok but how to do not use  Cloudant class for access to the cloudant api because we had couchdb-nano

```
const Cloudant = require("@cloudant/cloudant");
const username = "gggggg6-0600-4e1a-8ac6-8069a58fe0d2-bluemix";
const password =
  "--";
const url =
  "https://ggggg6-0600-4e1a-8ac6-8069a58fe0d2-bluemix:--@ggggggg936-0600-4e1a-8ac6-8gggggggg0d2-bluemix.cloudantnosqldb.appdomain.cloud";
const cloudant = Cloudant({ url: url, username: username, password: password });
```

##  Environment
heroku
local execution
expressjs

**Comment by rnewson** [comment]
Please don't paste passwords (or the vast majority of a password) to public repositories.

We'll look into the ticket shortly, I've scrubbed the comment and all history but I think you should rotate your password as a precaution.

**Comment by glynnbird** [comment]
To answer the original question, Nano definitely _does_ work with https. Please make sure you're using the latest version - I've just tried it and it works fine.

```js
const db = require('nano')(url).use('mydb');
db.list({limit:1}).then(console.log)
// { total_rows: 23200, offset: 0, rows: [...] }
```
