### ISSUE TITLE
Allow forcing GET on VIEW commands (even with keys)

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#24]
[Original issue](https://github.com/dscape/nano/issues/321)

__libHive__
This issue rose when working against Cloudant. Their pricing is 5 times cheaper for GET requests than POST requests. I had a lot of requests for small sets of keys, nothing that couldn't go into a query string, and I had made this change in order to keep my bills down.

The actual change was rather small - just adding an optional parameter to the request -
```javascript
  let exampleQuery = { 
            reduce : true, 
            group : true, 
            keys : [ [a,b], [c,d] ], 
            forceGet: true // this is the parameter I added
        }; 
```
Do you think this is something that should go into the main branch ?
Thanks

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
