### ISSUE TITLE
Nano not destroy docs completely   

### ISSUE THREAD

**Issue by rupamking1** [apache/couchdb-nano#262]
I watch delete docs is still available in my database.
<img width="333" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/113844818-85d16e80-97b2-11eb-93d7-b144134b5eb9.png">

**Comment by glynnbird** [comment]
That's the way Couchdb works. When a document is deleted it is only marked
as deleted so that replication of deletions can succeed.

**Comment by rupamking1** [comment]
@glynnbird Please tell me how to delete docs completely from the database & replicas, is that possible or not.

**Comment by glynnbird** [comment]
There is a "purge" API but it's not really designed for day-to-day usage, but for removing problematic documents. https://docs.couchdb.org/en/stable/api/database/misc.html#db-purge

The "normal" delete operation creates a new document revision, marking the document as deleted. CouchDB, as it stands today, isn't designed to completely delete documents.
