### ISSUE TITLE
Support for mango index creation

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#27]
[Original issue](https://github.com/dscape/nano/issues/330)

__chrisfosterelli__
Related to #dscape/nano/329

To create mango indices to query on, you have to POST http://couchdb/dbname/_index. This isn't possible right now, since nano's insert changes the method to PUT if a document ID is provided.

A temporary workaround is to call the relax method directly, but a better long term solution would be if nano added support for mango index creation.

Something like this might work:
```javascript
const couch = nano(url)
couch.use(db).mango.createIndex({ ... }, err => {
  // handle err
})
```

**Comment by janl** [comment]
Done https://github.com/apache/couchdb-nano#dbcreateindexindexdef-callback
