### ISSUE TITLE
Several README links direct to a 404 page or are inactive

### ISSUE THREAD

**Issue by brnnnfx** [apache/couchdb-nano#289]
Several README links direct to a 404 page or are inactive

## Expected Behavior
As an adopter and prospective contributor, I expect all links in documentation to be active to connect me with information I need to know, and for all badges and images to appear.

## Current Behavior
- Several links direct to error pages
- There are three badge icons that appear as broken images

## Possible Solution
Replace the dead links with active links && restore badges

OR

Remove the links from the document if there is no suitable replacement that is active

## Steps to Reproduce 
1. Navigate to https://github.com/apache/couchdb-nano/blob/main/README.md
2. Look at the first line of the document
3. Select hyperlink text `Coverage` to open the linked page

BUGS:
🐞 The badge icon beside `Coverage` appears as a broken image icon
🐞 The hyperlink directs you to an error page instead of a page with information about code coverage

![deadlink2](https://user-images.githubusercontent.com/12024098/148498829-049ffd9f-4206-439a-83cd-61dfea34ad94.png)
![deadlink1](https://user-images.githubusercontent.com/12024098/148498831-8fd393d0-a225-4be2-8fe7-4216f5dc9b1a.png)

The following links are dead / inactive:
| Line     | Link text                                        | URL                                                                         |
|:--------:|:---------------------------------------------:|:------------------------------------------------------------------:|
| 1        | `Build Status`                                  | https://travis-ci.org/github/apache/couchdb-nano  |
| 1        | `Coverage`                                      | https://img.shields.io/badge/coverage-100%-ff69b4.svg |
| 1        | `dependencies Status`                    | https://david-dm.org/apache/couchdb-nano/status.svg)](https://david-dm.org/apache/couchdb-nano |
| 192    | `futon`                                              | http://localhost:5984/_utils |
| 1316  | `document update handler support` | http://jackhq.tumblr.com/post/16035106690/nano-v1-2-x-document-update-handler-support-v1-2-x |
| 1319 | `adding copy to nano`                        | http://blog.jlank.com/2012/07/04/adding-copy-to-nano/ |
| 1343 | `Build Status`                                     | https://travis-ci.org/apache/couchdb-nano.svg?branch=main)](https://travis-ci.org/apache/couchdb-nano |
| 1344 | `dependencies Status`                      | https://david-dm.org/apache/couchdb-nano/status.svg)](https://david-dm.org/apache/couchdb-nano |

**Comment by glynnbird** [comment]
A great issue @brnnnfx ! Feel free to submit a PR removing the dodgy badges and dead links.
