### ISSUE TITLE
Handle ECONNRESET errors

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#29]
[Original issue](https://github.com/dscape/nano/issues/332)

__fhahne__
I may be missing something here, but it seems that nano is not handling ECONNRESET errors, or other sorts of socket hangups. I assume that one would want to attach an error listener to the request object in order to do so. Since that is all encapsulated in the module I am not quite sure how to archive that. Any suggestions?

__bmiller59__
+1 I am also getting similar errors. What is the correct strategy for adding an error handler to address these econnreset errors? Also, any suggestions what the cause could be?

__0x1mason__
can you do something like
```javascript
require('nano')({
request: function () {
  // request wrapper with special handling
}
})
```

**Comment by pfuntner** [comment]
How does the issue manifest?  I'm seeing some odd behavior doing a `nano.get()` with a callback.  The callback doesn't get invoked and I have no idea why.  Might this be an example of an error that isn't properly reported through the callback?

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
