### ISSUE TITLE
nano.head() and "/" (forwardslash) characters

### ISSUE THREAD

**Issue by leapinweasel** [apache/couchdb-nano#291]
I'm failing to use the head() command in documents with "/" in the id.  The document exists, but always returns null, as the method does not replace the "/" command with %2F.  I tried to escape it myself before passing, and then it does escape the "%" value and still fails to find.

I'm using an older version, I haven't been able to upgrade yet, but I couldn't find anything in recent release notes for this issue.

## Expected Behavior
head() method should find documents with IDs containing "/" characters.

## Current Behavior
head() always returns null when looking for documents with "/" in the ID.

## Steps to Reproduce (for bugs)
_Please note my javascript is not good._

const db = nano.use("mydatabase");
await db.insert({ _id: "TEST/DOC" });
let result = await db.head("TEST/DOC");

## Context
Our real world data exists in a system which allows "/" in names.  We use couchdb in an integration environment, but can't work with this data.

## Your Environment
* Version used: 8.1.0
* Browser Name and version:  node.js
* Operating System and version (desktop or mobile): node.js on linux
* Link to your project:

**Comment by glynnbird** [comment]
This definitely works fine on the 9.x releases, just tested it :)

**Comment by leapinweasel** [comment]
Thank you very much!
