### ISSUE TITLE
After calling changesReader.stop the HTTP connection remains open until the next HTTP longpoll timeout

### ISSUE THREAD

**Issue by insidewhy** [apache/couchdb-nano#309]
1. Follow changes to a database via `changesReader.start`
2. Stop listening to changes via `changesReader.stop`

After this the HTTP connection remains open for up to `opts.timeout` seconds (by default, 60 seconds). The `stop` event is only emitted from the change emitter after this.

We have integration tests that include `changesReader`. It's not possible to destroy the database between tests because the HTTP connection remains open and eventually leads to an uncaught error. We can't wait for the changes reader to stop because it takes about 60 seconds which makes our tests too slow.

Submitted a fix using `AbortController` (see https://axios-http.com/docs/cancellation) here https://github.com/apache/couchdb-nano/pull/310

**Comment by glynnbird** [comment]
Fixed in 10.1.0
