### ISSUE TITLE
Missing doc for nano.info

### ISSUE THREAD

**Issue by crystalfp** [apache/couchdb-nano#330]
## Expected Behavior
I expect the documentation be there and that the link from the beginning of the documentation points to it.

## Current Behavior
In the Table of Contents of <https://www.npmjs.com/package/nano> the link marked as [`nano.info([callback])`](https://www.npmjs.com/package/nano#nanoinfocallback) points to nothing.

Also looking at the whole page there is no documentation for this function.

## Possible Solution
- provide the documentation
- fix the link

## Steps to Reproduce (for bugs)

1. Go to the page <https://www.npmjs.com/package/nano>
2. Click on the `nano.info([callback])` entry
3. Nothing happens

## Context
Searching for a way to check when the db has no indexer tasks active to launch an heavy update.

## Your Environment

* Version used: nano: 10.1.2, couchdb: 3.3.1
* Browser Name and version: Chrome Version 112.0.5615.121 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop Windows 11 64 bits
* Link to your project: private

**Comment by glynnbird** [comment]
Fixed! thanks for raising.
