### ISSUE TITLE
Error after upgrade:  socket.setKeepAlive is not a function

### ISSUE THREAD

**Issue by reggi** [apache/couchdb-nano#345]
> Error: error happened in your connection. Reason: socket.setKeepAlive is not a function

I'm not sure why but after upgrade I'm seeing this error, if anyone knows what I need to do it would be great help!

**Comment by reggi** [comment]
maybe because of this call here https://github.com/axios/axios/blob/main/lib/adapters/http.js#L397 😠

**Comment by reggi** [comment]
nano@10.1.3

**Comment by glynnbird** [comment]
I'm not able to reproduce this. Can you share a small code snippet that triggers this? What version of node are you running?

**Comment by glynnbird** [comment]
Ha ha. No problem
