### ISSUE TITLE
db.multipart.get does not work with Cloudant Local 1.0.0.5

### ISSUE THREAD

**Issue by carlosduclos** [apache/couchdb-nano#35]
[Original issue](https://github.com/dscape/nano/issues/348)

__yawenchien__
Version

Cloudant Local 1.0.0.5
Cloudant 1.3 http://github.com/cloudant/nodejs-cloudant
nano 6.1.5
Issue
db.multipart.insert creates doc successfully & correctly in Cloudant Local 1.0.0.5. However, db.multipart.get does not return error code but does not retrieve correct/readable doc.

Workaround
Use https://$HOST/$DATABASE/$DOCUMENT_ID and https://$HOST/$DATABASE/$DOCUMENT_ID/FullContent to retrieve doc & its attachment.

**Comment by ricellis** [comment]
This was probably fixed by #83 if someone wants to try it out and verify.

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
