### ISSUE TITLE
Destroying An Undefined Doc Removes the Whole Database

### ISSUE THREAD

**Issue by maggiejiangtda** [apache/couchdb-nano#40]
Recently discovered a bug when trying to delete a doc from a CouchDB database. The action of deleting a document with "undefined" inputs actually removes the whole database. The <dbName>.destroy() call should really be restricted to destroying documents and not the whole DB itself.  If an undefined is sent in, I think nano should ideally return an error?  

This is a sample code to reproduce what happens:

const nano = require( 'nano' )( CouchDB );
const dbName = nano.db.use( 'dbName' );

dbName.destroy( undefined, undefined, ( err ) => {
  **//DB is destroyed at this point**
} );

**Comment by ramdesh** [comment]
On close inspection, I found that the HTTP request that goes to the database if the id is undefined, is the same as the database delete request: 
`{ method: 'DELETE',
  headers:
   { 'content-type': 'application/json',
     accept: 'application/json' },
  uri: 'https://{username}.cloudant.com/{database-name}',
  qs: { rev: undefined } }`

**Comment by ColoradoFlyer** [comment]
This is the same issue I just opened (#181) -- with rather catastrophic results (deleting the entire _replicator database is kinda bad, IMHO).

Open for 2 years now?

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
