### ISSUE TITLE
Greedy URL parser

### ISSUE THREAD

**Issue by cboden** [apache/couchdb-nano#41]
When passing a URL to the parser (from couchdb-bootstrap) it's grabbing the first `/` it finds and improperly returning a parsed URL when I have a `/` in my password. 
> 'http://admin:28vBiMbx3h/4=tRPdAfZ7PWrMrxq;BAa+Ru@localhost:5984'
```
  config: 
   { url: 'http://admin/:28vBiMbx3h',
     db: '4=tRPdAfZ7PWrMrxq;BAa+Ru@localhost:5984',
     defaultHeaders: { 'X-Couch-Full-Commit': 'true' } }
```

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
