### ISSUE TITLE
Remote Memory Exposure in nano@6.3.0 > follow@0.12.1 > request@2.55.0

### ISSUE THREAD

**Issue by konrad-2013** [apache/couchdb-nano#48]
Hi,

I am checking my projects with [nsp](https://www.npmjs.com/package/nsp) and get the following findings.

![selection_010](https://user-images.githubusercontent.com/4664081/27747969-d08b69bc-5dcd-11e7-96cb-805edbc8ffdb.png)

Could you please update dependencies or remove the follow module if possible?
It looks like that the project is no longer active, the same issue was reported on Jun 10, 2016 at the follow project https://github.com/iriscouch/follow/issues/84.
The last commit on master was on May 24, 2015.

https://nodesecurity.io/advisories/309
https://nodesecurity.io/advisories/77

Thanks in advance
Konrad

**Comment by janl** [comment]
Should we switch to cloudant-follow? https://github.com/cloudant-labs/cloudant-follow

**Comment by janl** [comment]
PR here: https://github.com/apache/couchdb-nano/pull/51

**Comment by konrad-2013** [comment]
Cool thanks for figuring that out.
:+1: for PR #51

**Comment by konrad-2013** [comment]
@dscape could you have a look please?

**Comment by dscape** [comment]
I can have a look, but since I'm no longer a maintainer would be good to understand what the scope is! Appreciate the feedback

**Comment by loay** [comment]
@dscape 
There are security vulnerabilities. 
```
(+) 2 vulnerabilities found
 Name      Installed   Patched                      Path                                                       More Info                              
 request   2.55.0      >=2.68.0                     nano@6.3.0 > follow@0.12.1 > request@2.55.0                https://nodesecurity.io/advisories/309 
 hawk      2.3.1       >=3.1.3 < 4.0.0 || >=4.1.1   nano@6.3.0 > follow@0.12.1 > request@2.55.0 > hawk@2.3.1   https://nodesecurity.io/advisories/77  

```

Even if we update to the last version of `follow`, it won't fix the issue, since `follow` is using an outdated versions of `request` and `hawk` .. so we need `follow` to update or to use another library instead of `follow`.

**Comment by loay** [comment]
The related pr is being merged: https://github.com/apache/couchdb-nano/pull/51
Can the release team let us know when it will be released so the security changes take effect? Thank you

**Comment by garrensmith** [comment]
6.4.2 fixes this

**Comment by konrad-2013** [comment]
Thanks for fixing :-)
