### ISSUE TITLE
Feature: CouchDB 2.0 - Multiple View Queries

### ISSUE THREAD

**Issue by dainyl** [apache/couchdb-nano#55]
CouchDB 2.0 now supports bulk querying views via http://docs.couchdb.org/en/2.0.0/api/ddoc/views.html#api-ddoc-view-multiple-queries

## Expected Behavior
This would work via the `db.view` function https://github.com/apache/couchdb-nano#dbviewdesignname-viewname-params-callback

## Current Behavior
`db.view` assumes that it's a GET request, but a POST request is required

## Possible Solution
Update `db.view` to perform a POST request if `queries` is present in `params`

**Comment by janl** [comment]
Closing in favor of #56
