### ISSUE TITLE
db.view encodes start_key / startkey and end_key / endkey params differently

### ISSUE THREAD

**Issue by blakew** [apache/couchdb-nano#65]
I have a composite key view aka key = [id, 0], [id, 1], .... When I use the start_key alias (with underscore), the uri encoding is incorrect. startkey passes the correct encoding.

```
    db.view(designdoc, viewname, {
        start_key: [req.params.id],
        end_key: [req.params.id, {}],
        include_docs: true,
    }, callback);
```
(incorrectly) encodes to `start_key[0]=id&end_key[0]=id` which in fact returns *all* documents in the view.

```
    db.view(designdoc, viewname, {
        startkey: [req.params.id],
        endkey: [req.params.id, {}],
        include_docs: true,
    }, callback);
```
(correctly) encodes to `startkey=[id]&endkey=[id, {}]` and returns the correct documents.

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
