### ISSUE TITLE
Is a native promise version planned

### ISSUE THREAD

**Issue by ForsakenHarmony** [apache/couchdb-nano#66]
It's generally known that callbacks lead to bad code
also promisifying callback functions makes it (slower and) harder to debug given the stack traces

**Comment by beetaa** [comment]
I want to ask the same question. Why there's no answer?

**Comment by beetaa** [comment]
Is this project still under maintain?

**Comment by sarics** [comment]
I had the same problem, so I looked around in the code, and found that there is a `request` config option, so you can use other request-like module, [request-promise-native](https://www.npmjs.com/package/request-promise-native) for example.
And, for every function, nano simply returns the request call.

So, if you combine the two, you have a promisified nano 🎉:
```javascript
const nano = require('nano');
const request = require('request-promise-native');

const couch = nano({
  url: 'http://localhost:5984',
  // requestDefaults can't be used here, pass request.defaults({...}) to request instead
  request: request.defaults({
    resolveWithFullResponse: true, // set to false if you only need the response body
    json: true,
  }),
});

couch.use('_users').info()
  .then(({ headers, body }) => {
    console.log(headers, body);
  });
```

**Comment by janl** [comment]
This is nice, wanna maybe add this to the README? Happy to merge a PR.

**Comment by janl** [comment]
Yes, 7.0.0 just came out with native promise support
