### ISSUE TITLE
Documentation for atomic method is wrong

### ISSUE THREAD

**Issue by blakew** [apache/couchdb-nano#67]
```atomic``` documentation refers to request.form directly. Instead the method stringifies the object in req.body. So in your update handler, you need to insert:

```
var body = JSON.parse(req.body);
```

In addition to this issue with the docs is there any particular reason why the object body is stringified? 

Thanks

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
