### ISSUE TITLE
Or-Clauses

### ISSUE THREAD

**Issue by sbatururimi** [apache/couchdb-nano#71]
I spent several hours trying to figure out how to use the OR condition and accidentally discovered it

## Possible Solution
https://github.com/dscape/nano/issues/357
I propose to include such explanation in the doc.

**Comment by janl** [comment]
@sbatururimi wanna submit a PR against the README?

**Comment by sbatururimi** [comment]
Not really. Just propose to add that to the README.

**Comment by garrensmith** [comment]
I'm going to close this. Since its not an actual issue. It would be great if you could send us a PR for this @sbatururimi
