### ISSUE TITLE
Add the typescript definitions into nano repo

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-nano#77]
Typescript is a pretty popular programming language now and it is important to keep the type definitions up to date. I think it would be a lot easier to maintain the definitions if they are in the nano repo. 

Would any of the original authors and contributors of the definitions be willing to send us a starting PR for the definitions from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nano/index.d.ts)

cc @timjacobi @vincekovacs @dsabanin @gyszalai @ccodin @domachine @andy-ms @smithsz

**Comment by ccodin** [comment]
Hi,

I'm not a major contributor (1 commit haha...) but i think it could be very useful. 

Indeed some of the definitions are still missing, and I (shamely) patched them in node_modules directly. Why ? Cause I'm lazy, but guess the surprise when I npm build on a new machine \o/

If nano can have its definitions, it could prevent some issues
Anyway, +1 for the enhancement

**Comment by janl** [comment]
Done
