### ISSUE TITLE
CouchDB docker image returns incorrect response for multiple view queries

### ISSUE THREAD

**Issue by adamsaeid** [apache/couchdb-nano#79]
The CouchDB image used by [scripts/run_couchdb_on_travis.sh](https://github.com/apache/couchdb-nano/blob/master/scripts/run_couchdb_on_travis.sh) returns an incorrectly formatted response when sending multiple queries to a view.

## Expected Behavior
Response should be an object like this:

` results: [
    {total_rows:3,offset:0,rows:[{id:"p_derek",key:["Derek","San Francisco"],value:"p_derek"},{id:"p_nuno",key:["Nuno","London"],value:"p_nuno"}]},
    {total_rows:3,offset:2,rows:[{id:"p_randall",key:["Randall","San Francisco"],value:"p_randall"}]}
  ]`

## Current Behavior
Response is a string like this:

 '{"results":[\r\n{"total_rows":3,"offset":0,"rows":[\r\n{"id":"p_derek","key":["Derek","San Francisco"],"value":"p_derek"},\r\n{"id":"p_nuno","key":["Nuno","London"],"value":"p_nuno"}\r\n]},\r\n{"id":"p_randall","key":["Randall","San Francisco"],"value":"p_randall"}\r\n]}\r\n]}\n'

## Possible Solution
Change run_couchdb_on_travis.sh and test against a different CouchDB image

(edited for clarity)

## Steps to Reproduce (for bugs)

Start the currently used CouchDB docker image:
`docker run --ulimit nofile=2048:2048 -d -p 5984:5984 klaemo/couchdb:2.0-dev@sha256:336fd3d9a89475205fc79b6a287ee550d258fac3b62c67b8d13b8e66c71d228f --with-haproxy \
--with-admin-party-please -n 1`
 
Run the test on my [fork](https://github.com/adamsaeid/couchdb-nano/tree/multi-view-queries):
`NOCK_OFF=true node tests/integration/design/query.js`

The test fails.

Now switch to using the [official CouchDB docker image](https://hub.docker.com/_/couchdb/):
`docker kill $(docker ps -q)`
`docker run -d -p 5984:5984 couchdb `

Run the test again and it passes

## Context
Trying to write tests for[ multiple query views](https://github.com/apache/couchdb-nano/pull/56)

## Your Environment
Saw this on default AWS Cloud9 dev environment.

**Comment by wohali** [comment]
Indeed, the klaemo image is long since retired.

You need to be running against `apache/couchdb:2.1.1` or simply `couchdb:2.1.1` which are the same image.

**Comment by adamsaeid** [comment]
@glynnbird think this can be closed now the script is updated 🙂

**Comment by glynnbird** [comment]
Thanks @adamsaeid & @wohali. The testing harness now uses the official CouchDB Docker image.
