### ISSUE TITLE
Complete the documentation for Typescript and missing methods like find()

### ISSUE THREAD

**Issue by weber-d** [apache/couchdb-nano#84]
I'm using nano 6.4.3 on typescript 2.8.1. By having the need to filter/organize the data, I saw in the type-definitions, that we've suiteable methods like `find()`. But there is a lack of documentation. Couldn't find anything about it in the official docs here and also not on other ressources like SO. Since I need to use CouchDb and I can't find any other driver, I did reverse engineering how to use it: 

```ts
class MyEntity {
    name: string = ''
}
let query: nano.MangoQuery = {
  selector: { name: 'Peter' }
};
let nanoDb = <nano.DocumentScope<MyEntity>>nano('http://localhost:5984/mydb')
nanoDb.find(
  query,
  (err, data: nano.MangoResponse<MyEntity>) => {
    console.log("Response");
    console.log(err);
    console.log(data);
  }
);
```

It seems to work fine. Please add those method to our documentation. As a Typescript developer, I'd very pleased if you add the Typescript syntax, instead of having only the legacy Javascript examples. It's time sensitive to search in the typedefinitions on my own and play around to make it work. Normally I use full Typescript compatible and documentet librarys, there it's easy and much faster to get started. 

### Environment 
I don't think it's important since we're talking about documentation and not code-issues itself. But here the list of all my installed packages for testing purpose: 

```json
{
    "nano": "^6.4.3",
    "@types/nano": "^6.4.5",
    "typescript": "^2.8.1"
}
```

**Comment by big-r81** [comment]
I'm closing this old ticket. If it's still a problem, please reopen or create a new ticket.
