### ISSUE TITLE
documentation for /db/_revs_limit  

### ISSUE THREAD

**Issue by SK-CSE** [apache/couchdb-nano#89]
i am new to couch db and i want to set the limit of historical revisions to store for a single document in the database. i am not sure how to do that with nano. any help would be appreciated.

**Comment by glynnbird** [comment]
The `GET /db/_revs_limit` tells you how many document revision tombstones are retained by the database. Older document bodies are recovered by compacting the database periodically, but "tombstone" documents are retained to prevent deleted documents resurrecting themselves during replication. 

Compaction docs [here](http://docs.couchdb.org/en/2.1.1/maintenance/compaction.html?highlight=_revs_limit). There's no specific function call for this in Nano, but you can make a [custom request](https://github.com/apache/couchdb-nano#nanorequestopts-callback) if you wish.

**Comment by SK-CSE** [comment]
yeah.. i have already made custom request for the same. i appreciate your response.. :)
